version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/containers_by_bazel

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/.cache
      - run:
          name: Install bazel
          command: |
            echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
            curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
            sudo apt-get update
            sudo apt-get install bazel
            bazel info release
      - run:
          name: Build binary
          command: |
            bazel build :hello
      - run:
          name: Build container image with go_image base
          command: |
            bazel build :go_image
      - save_cache:
          key: v1-{{ .Branch }}
          paths:
            - ~/.cache

  # deploy:
  #   docker:
  #     - image: google/cloud-sdk
  #   working_directory: ~/orangeapi
  #   environment:
  #     PROJECT_NAME: saas-orangesys-io
  #     CLUSTER_NAME: orangesys-io
  #     CLOUDSDK_COMPUTE_ZONE: asia-northeast1-c
  #     ORG_PATH: "github.com/orangesys"
  #     REPO_PATH: "${ORG_PATH}/orangeapi"
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: 17.07.0-ce
  #     - restore_cache:
  #         keys:
  #           - v1-{{ .Branch }}
  #         paths:
  #           - /caches/alpine-orangeapi.tar
  #     - run:
  #         name: Install docker client
  #         command: |
  #           set -x
  #           VER="17.07.0-ce"
  #           curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/edge/x86_64/docker-${VER}.tgz
  #           tar -xz -C /tmp/ -f /tmp/docker-$VER.tgz
  #           mv /tmp/docker/* /usr/bin
  #     - run:
  #         name: Push docker hub
  #         command: |
  #           docker login -u $DOCKER_USER -p $DOCKER_PASS
  #           docker push orangesys/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
  #           curl -X POST https://hooks.microbadger.com/images/orangesys/alpine-orangeapi/_24B4d4BBsQhsH6Av_nH1ZKsl2s=
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
      # - build_container:
      #     requires:
      #       - build_orangeapi
      #     filters:
      #       tags:
      #         only: /^v[0-9]+(\.[0-9]+)*/
      # - deploy:
      #     requires:
      #       - build_orangeapi
      #       - build_container
      #     filters:
      #       tags:
      #         only: /^v[0-9]+(\.[0-9]+)*/
      #       branches:
      #         ignore: /.*/
