version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/containers_by_bazel

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/.cache
      - run:
          name: Install bazel
          command: |
            echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
            curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
            sudo apt-get update
            sudo apt-get install bazel
            bazel info release
      - run:
          name: Build binary
          command: |
            bazel build :hello
      - run:
          name: Build container image with go_image base
          command: |
            bazel build :go_image
      - save_cache:
          key: v1-{{ .Branch }}
          paths:
            - ~/.cache
  deploy:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/.cache
      - run:
          name: Install bazel
          command: |
            echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
            curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
            sudo apt-get update
            sudo apt-get install bazel
            bazel info release
      - run:
          name: Push docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bazel run :push_bundle
            # curl -X POST https://hooks.microbadger.com/images/orangesys/alpine-orangeapi/_24B4d4BBsQhsH6Av_nH1ZKsl2s=
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
